export const APP_ROUTES = {
  DUE_DETAIL: '/dues/:id',
  DUE_LIST: '/dues',
  DUE_NEW: '/dues/new',
  DUES_LIST: '/dues',
  DUES_NEW: '/dues/new',
  HOME: '/',
  LOGIN: '/auth/login',
  LOGOUT: '/auth/logout',
  MEMBER_DETAIL: '/members/:id',
  MEMBER_LIST: '/members',
  MEMBER_NEW: '/members/new',
  MOVEMENT_LIST: '/movements',
  MOVEMENT_NEW: '/movements/new',
  PAYMENT_LIST: '/payments',
  PAYMENT_NEW: '/payments/new',
  PAYMENTS_LIST: '/payments',
  PAYMENTS_NEW: '/payments/new',
  PROFILE: '/profile',
  USER_DETAIL: '/users/:id',
  USER_LIST: '/users',
  USER_NEW: '/users/new',
} as const;

export type AppRoutes = typeof APP_ROUTES;
