export const DIToken = Object.freeze({
  IDueRepository: Symbol('IDueRepository'),
  IEmailRepository: Symbol('IEmailRepository'),
  IEmailService: Symbol('IEmailService'),
  IEventRepository: Symbol('IEventRepository'),
  ILoggerService: Symbol('ILoggerService'),
  IMemberCreditRepository: Symbol('IMemberCreditRepository'),
  IMemberRepository: Symbol('IMemberRepository'),
  IMeteorUsers: Symbol('IMeteorUsers'),
  IMovementRepository: Symbol('IMovementRepository'),
  INotificationRepository: Symbol('INotificationRepository'),
  IPaymentRepository: Symbol('IPaymentRepository'),
  IPriceCategoryRepository: Symbol('IPriceCategoryRepository'),
  IPriceRepository: Symbol('IPriceRepository'),
  IUnitOfWork: Symbol('IUnitOfWork'),
  IUserRepository: Symbol('IUserRepository'),
});
