export const MemberStatus = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
} as const;

export type MemberStatus = (typeof MemberStatus)[keyof typeof MemberStatus];

export const MemberStatusLabel = {
  [MemberStatus.ACTIVE]: 'Activo',
  [MemberStatus.INACTIVE]: 'Inactivo',
} as const;

export const MemberStatusSort = {
  [MemberStatus.ACTIVE]: 1,
  [MemberStatus.INACTIVE]: 2,
} as const;

export const MemberStatusSorted = Object.values(MemberStatus).sort(
  (a, b) => MemberStatusSort[a] - MemberStatusSort[b],
);

export const MemberCategory = {
  ADHERENT_MEMBER: 'adherent-member',
  CADET: 'cadet',
  MEMBER: 'member',
  PRE_CADET: 'pre-cadet',
} as const;

export type MemberCategory =
  (typeof MemberCategory)[keyof typeof MemberCategory];

export const MemberCategoryLabel = {
  [MemberCategory.ADHERENT_MEMBER]: 'Adherente',
  [MemberCategory.CADET]: 'Cadete',
  [MemberCategory.MEMBER]: 'Socio',
  [MemberCategory.PRE_CADET]: 'Pre-cadete',
} as const;

export const MemberCategorySort = {
  [MemberCategory.ADHERENT_MEMBER]: 4,
  [MemberCategory.CADET]: 2,
  [MemberCategory.MEMBER]: 1,
  [MemberCategory.PRE_CADET]: 3,
} as const;

export const FileStatus = {
  COMPLETED: 'completed',
  PENDING: 'pending',
} as const;

export type FileStatus = (typeof FileStatus)[keyof typeof FileStatus];

export const FileStatusLabel = {
  [FileStatus.COMPLETED]: 'Completado',
  [FileStatus.PENDING]: 'Pendiente',
} as const;

export const MemberNationality = {
  AFGHANISTAN: 'afghanistan',
  ALBANIA: 'albania',
  ALGERIA: 'algeria',
  ANDORRA: 'andorra',
  ANGOLA: 'angola',
  ANTIGUA_AND_BARBUDA: 'antigua-and-barbuda',
  ARGENTINA: 'argentina',
  ARMENIA: 'armenia',
  AUSTRALIA: 'australia',
  AUSTRIA: 'austria',
  AZERBAIJAN: 'azerbaijan',
  BAHAMAS: 'bahamas',
  BAHRAIN: 'bahrain',
  BANGLADESH: 'bangladesh',
  BARBADOS: 'barbados',
  BELARUS: 'belarus',
  BELGIUM: 'belgium',
  BELIZE: 'belize',
  BENIN: 'benin',
  BHUTAN: 'bhutan',
  BOLIVIA: 'bolivia',
  BOSNIA_AND_HERZEGOVINA: 'bosnia-and-herzegovina',
  BOTSWANA: 'botswana',
  BRAZIL: 'brazil',
  BRUNEI: 'brunei',
  BULGARIA: 'bulgaria',
  BURKINA_FASO: 'burkina-faso',
  BURUNDI: 'burundi',
  CABO_VERDE: 'cabo-verde',
  CAMBODIA: 'cambodia',
  CAMEROON: 'cameroon',
  CANADA: 'canada',
  CENTRAL_AFRICAN_REPUBLIC: 'central-african-republic',
  CHAD: 'chad',
  CHILE: 'chile',
  CHINA: 'china',
  COLOMBIA: 'colombia',
  COMOROS: 'comoros',
  CONGO: 'congo',
  COSTA_RICA: 'costa-rica',
  CROATIA: 'croatia',
  CUBA: 'cuba',
  CYPRUS: 'cyprus',
  CZECH_REPUBLIC: 'czech-republic',
  DEMOCRATIC_REPUBLIC_OF_THE_CONGO: 'democratic-republic-of-the-congo',
  DENMARK: 'denmark',
  DJIBOUTI: 'djibouti',
  DOMINICA: 'dominica',
  DOMINICAN_REPUBLIC: 'dominican-republic',
  EAST_TIMOR: 'east-timor',
  ECUADOR: 'ecuador',
  EGYPT: 'egypt',
  EL_SALVADOR: 'el-salvador',
  EQUATORIAL_GUINEA: 'equatorial-guinea',
  ERITREA: 'eritrea',
  ESTONIA: 'estonia',
  ESWATINI: 'eswatini',
  ETHIOPIA: 'ethiopia',
  FIJI: 'fiji',
  FINLAND: 'finland',
  FRANCE: 'france',
  GABON: 'gabon',
  GAMBIA: 'gambia',
  GEORGIA: 'georgia',
  GERMANY: 'germany',
  GHANA: 'ghana',
  GREECE: 'greece',
  GRENADA: 'grenada',
  GUATEMALA: 'guatemala',
  GUINEA: 'guinea',
  GUINEA_BISSAU: 'guinea-bissau',
  GUYANA: 'guyana',
  HAITI: 'haiti',
  HONDURAS: 'honduras',
  HUNGARY: 'hungary',
  ICELAND: 'iceland',
  INDIA: 'india',
  INDONESIA: 'indonesia',
  IRAN: 'iran',
  IRAQ: 'iraq',
  IRELAND: 'ireland',
  ISRAEL: 'israel',
  ITALY: 'italy',
  IVORY_COAST: 'ivory-coast',
  JAMAICA: 'jamaica',
  JAPAN: 'japan',
  JORDAN: 'jordan',
  KAZAKHSTAN: 'kazakhstan',
  KENYA: 'kenya',
  KIRIBATI: 'kiribati',
  KOSOVO: 'kosovo',
  KUWAIT: 'kuwait',
  KYRGYZSTAN: 'kyrgyzstan',
  LAOS: 'laos',
  LATVIA: 'latvia',
  LEBANON: 'lebanon',
  LESOTHO: 'lesotho',
  LIBERIA: 'liberia',
  LIBYA: 'libya',
  LIECHTENSTEIN: 'liechtenstein',
  LITHUANIA: 'lithuania',
  LUXEMBOURG: 'luxembourg',
  MADAGASCAR: 'madagascar',
  MALAWI: 'malawi',
  MALAYSIA: 'malaysia',
  MALDIVES: 'maldives',
  MALI: 'mali',
  MALTA: 'malta',
  MARSHALL_ISLANDS: 'marshall-islands',
  MAURITANIA: 'mauritania',
  MAURITIUS: 'mauritius',
  MEXICO: 'mexico',
  MICRONESIA: 'micronesia',
  MOLDOVA: 'moldova',
  MONACO: 'monaco',
  MONGOLIA: 'mongolia',
  MONTENEGRO: 'montenegro',
  MOROCCO: 'morocco',
  MOZAMBIQUE: 'mozambique',
  MYANMAR: 'myanmar',
  NAMIBIA: 'namibia',
  NAURU: 'nauru',
  NEPAL: 'nepal',
  NETHERLANDS: 'netherlands',
  NEW_ZEALAND: 'new-zealand',
  NICARAGUA: 'nicaragua',
  NIGER: 'niger',
  NIGERIA: 'nigeria',
  NORTH_KOREA: 'north-korea',
  NORTH_MACEDONIA: 'north-macedonia',
  NORWAY: 'norway',
  OMAN: 'oman',
  PAKISTAN: 'pakistan',
  PALAU: 'palau',
  PALESTINE: 'palestine',
  PANAMA: 'panama',
  PAPUA_NEW_GUINEA: 'papua-new-guinea',
  PARAGUAY: 'paraguay',
  PERU: 'peru',
  PHILIPPINES: 'philippines',
  POLAND: 'poland',
  PORTUGAL: 'portugal',
  QATAR: 'qatar',
  ROMANIA: 'romania',
  RUSSIA: 'russia',
  RWANDA: 'rwanda',
  SAINT_KITTS_AND_NEVIS: 'saint-kitts-and-nevis',
  SAINT_LUCIA: 'saint-lucia',
  SAINT_VINCENT_AND_THE_GRENADINES: 'saint-vincent-and-the-grenadines',
  SAMOA: 'samoa',
  SAN_MARINO: 'san-marino',
  SAO_TOME_AND_PRINCIPE: 'sao-tome-and-principe',
  SAUDI_ARABIA: 'saudi-arabia',
  SENEGAL: 'senegal',
  SERBIA: 'serbia',
  SEYCHELLES: 'seychelles',
  SIERRA_LEONE: 'sierra-leone',
  SINGAPORE: 'singapore',
  SLOVAKIA: 'slovakia',
  SLOVENIA: 'slovenia',
  SOLOMON_ISLANDS: 'solomon-islands',
  SOMALIA: 'somalia',
  SOUTH_AFRICA: 'south-africa',
  SOUTH_KOREA: 'south-korea',
  SOUTH_SUDAN: 'south-sudan',
  SPAIN: 'spain',
  SRI_LANKA: 'sri-lanka',
  SUDAN: 'sudan',
  SURINAME: 'suriname',
  SWEDEN: 'sweden',
  SWITZERLAND: 'switzerland',
  SYRIA: 'syria',
  TAIWAN: 'taiwan',
  TAJIKISTAN: 'tajikistan',
  TANZANIA: 'tanzania',
  THAILAND: 'thailand',
  TOGO: 'togo',
  TONGA: 'tonga',
  TRINIDAD_AND_TOBAGO: 'trinidad-and-tobago',
  TUNISIA: 'tunisia',
  TURKEY: 'turkey',
  TURKMENISTAN: 'turkmenistan',
  TUVALU: 'tuvalu',
  UGANDA: 'uganda',
  UKRAINE: 'ukraine',
  UNITED_ARAB_EMIRATES: 'united-arab-emirates',
  UNITED_KINGDOM: 'united-kingdom',
  UNITED_STATES: 'united-states',
  URUGUAY: 'uruguay',
  UZBEKISTAN: 'uzbekistan',
  VANUATU: 'vanuatu',
  VATICAN_CITY: 'vatican-city',
  VENEZUELA: 'venezuela',
  VIETNAM: 'vietnam',
  YEMEN: 'yemen',
  ZAMBIA: 'zambia',
  ZIMBABWE: 'zimbabwe',
} as const;

export type MemberNationality =
  (typeof MemberNationality)[keyof typeof MemberNationality];

export const MemberNationalityLabel = {
  [MemberNationality.AFGHANISTAN]: 'Afganistán',
  [MemberNationality.ALBANIA]: 'Albania',
  [MemberNationality.ALGERIA]: 'Argelia',
  [MemberNationality.ANDORRA]: 'Andorra',
  [MemberNationality.ANGOLA]: 'Angola',
  [MemberNationality.ANTIGUA_AND_BARBUDA]: 'Antigua y Barbuda',
  [MemberNationality.ARGENTINA]: 'Argentina',
  [MemberNationality.ARMENIA]: 'Armenia',
  [MemberNationality.AUSTRALIA]: 'Australia',
  [MemberNationality.AUSTRIA]: 'Austria',
  [MemberNationality.AZERBAIJAN]: 'Azerbaiyán',
  [MemberNationality.BAHAMAS]: 'Bahamas',
  [MemberNationality.BAHRAIN]: 'Baréin',
  [MemberNationality.BANGLADESH]: 'Bangladés',
  [MemberNationality.BARBADOS]: 'Barbados',
  [MemberNationality.BELARUS]: 'Bielorrusia',
  [MemberNationality.BELGIUM]: 'Bélgica',
  [MemberNationality.BELIZE]: 'Belice',
  [MemberNationality.BENIN]: 'Benín',
  [MemberNationality.BHUTAN]: 'Bután',
  [MemberNationality.BOLIVIA]: 'Bolivia',
  [MemberNationality.BOSNIA_AND_HERZEGOVINA]: 'Bosnia y Herzegovina',
  [MemberNationality.BOTSWANA]: 'Botsuana',
  [MemberNationality.BRAZIL]: 'Brasil',
  [MemberNationality.BRUNEI]: 'Brunéi',
  [MemberNationality.BULGARIA]: 'Bulgaria',
  [MemberNationality.BURKINA_FASO]: 'Burkina Faso',
  [MemberNationality.BURUNDI]: 'Burundi',
  [MemberNationality.CABO_VERDE]: 'Cabo Verde',
  [MemberNationality.CAMBODIA]: 'Camboya',
  [MemberNationality.CAMEROON]: 'Camerún',
  [MemberNationality.CANADA]: 'Canadá',
  [MemberNationality.CENTRAL_AFRICAN_REPUBLIC]: 'República Centroafricana',
  [MemberNationality.CHAD]: 'Chad',
  [MemberNationality.CHILE]: 'Chile',
  [MemberNationality.CHINA]: 'China',
  [MemberNationality.COLOMBIA]: 'Colombia',
  [MemberNationality.COMOROS]: 'Comoras',
  [MemberNationality.CONGO]: 'Congo',
  [MemberNationality.COSTA_RICA]: 'Costa Rica',
  [MemberNationality.CROATIA]: 'Croacia',
  [MemberNationality.CUBA]: 'Cuba',
  [MemberNationality.CYPRUS]: 'Chipre',
  [MemberNationality.CZECH_REPUBLIC]: 'República Checa',
  [MemberNationality.DEMOCRATIC_REPUBLIC_OF_THE_CONGO]:
    'República Democrática del Congo',
  [MemberNationality.DENMARK]: 'Dinamarca',
  [MemberNationality.DJIBOUTI]: 'Yibuti',
  [MemberNationality.DOMINICA]: 'Dominica',
  [MemberNationality.DOMINICAN_REPUBLIC]: 'República Dominicana',
  [MemberNationality.EAST_TIMOR]: 'Timor Oriental',
  [MemberNationality.ECUADOR]: 'Ecuador',
  [MemberNationality.EGYPT]: 'Egipto',
  [MemberNationality.EL_SALVADOR]: 'El Salvador',
  [MemberNationality.EQUATORIAL_GUINEA]: 'Guinea Ecuatorial',
  [MemberNationality.ERITREA]: 'Eritrea',
  [MemberNationality.ESTONIA]: 'Estonia',
  [MemberNationality.ESWATINI]: 'Esuatini',
  [MemberNationality.ETHIOPIA]: 'Etiopía',
  [MemberNationality.FIJI]: 'Fiyi',
  [MemberNationality.FINLAND]: 'Finlandia',
  [MemberNationality.FRANCE]: 'Francia',
  [MemberNationality.GABON]: 'Gabón',
  [MemberNationality.GAMBIA]: 'Gambia',
  [MemberNationality.GEORGIA]: 'Georgia',
  [MemberNationality.GERMANY]: 'Alemania',
  [MemberNationality.GHANA]: 'Ghana',
  [MemberNationality.GREECE]: 'Grecia',
  [MemberNationality.GRENADA]: 'Granada',
  [MemberNationality.GUATEMALA]: 'Guatemala',
  [MemberNationality.GUINEA]: 'Guinea',
  [MemberNationality.GUINEA_BISSAU]: 'Guinea-Bisáu',
  [MemberNationality.GUYANA]: 'Guyana',
  [MemberNationality.HAITI]: 'Haití',
  [MemberNationality.HONDURAS]: 'Honduras',
  [MemberNationality.HUNGARY]: 'Hungría',
  [MemberNationality.ICELAND]: 'Islandia',
  [MemberNationality.INDIA]: 'India',
  [MemberNationality.INDONESIA]: 'Indonesia',
  [MemberNationality.IRAN]: 'Irán',
  [MemberNationality.IRAQ]: 'Irak',
  [MemberNationality.IRELAND]: 'Irlanda',
  [MemberNationality.ISRAEL]: 'Israel',
  [MemberNationality.ITALY]: 'Italia',
  [MemberNationality.IVORY_COAST]: 'Costa de Marfil',
  [MemberNationality.JAMAICA]: 'Jamaica',
  [MemberNationality.JAPAN]: 'Japón',
  [MemberNationality.JORDAN]: 'Jordania',
  [MemberNationality.KAZAKHSTAN]: 'Kazajistán',
  [MemberNationality.KENYA]: 'Kenia',
  [MemberNationality.KIRIBATI]: 'Kiribati',
  [MemberNationality.KOSOVO]: 'Kosovo',
  [MemberNationality.KUWAIT]: 'Kuwait',
  [MemberNationality.KYRGYZSTAN]: 'Kirguistán',
  [MemberNationality.LAOS]: 'Laos',
  [MemberNationality.LATVIA]: 'Letonia',
  [MemberNationality.LEBANON]: 'Líbano',
  [MemberNationality.LESOTHO]: 'Lesoto',
  [MemberNationality.LIBERIA]: 'Liberia',
  [MemberNationality.LIBYA]: 'Libia',
  [MemberNationality.LIECHTENSTEIN]: 'Liechtenstein',
  [MemberNationality.LITHUANIA]: 'Lituania',
  [MemberNationality.LUXEMBOURG]: 'Luxemburgo',
  [MemberNationality.MADAGASCAR]: 'Madagascar',
  [MemberNationality.MALAWI]: 'Malaui',
  [MemberNationality.MALAYSIA]: 'Malasia',
  [MemberNationality.MALDIVES]: 'Maldivas',
  [MemberNationality.MALI]: 'Malí',
  [MemberNationality.MALTA]: 'Malta',
  [MemberNationality.MARSHALL_ISLANDS]: 'Islas Marshall',
  [MemberNationality.MAURITANIA]: 'Mauritania',
  [MemberNationality.MAURITIUS]: 'Mauricio',
  [MemberNationality.MEXICO]: 'México',
  [MemberNationality.MICRONESIA]: 'Micronesia',
  [MemberNationality.MOLDOVA]: 'Moldavia',
  [MemberNationality.MONACO]: 'Mónaco',
  [MemberNationality.MONGOLIA]: 'Mongolia',
  [MemberNationality.MONTENEGRO]: 'Montenegro',
  [MemberNationality.MOROCCO]: 'Marruecos',
  [MemberNationality.MOZAMBIQUE]: 'Mozambique',
  [MemberNationality.MYANMAR]: 'Birmania',
  [MemberNationality.NAMIBIA]: 'Namibia',
  [MemberNationality.NAURU]: 'Nauru',
  [MemberNationality.NEPAL]: 'Nepal',
  [MemberNationality.NETHERLANDS]: 'Países Bajos',
  [MemberNationality.NEW_ZEALAND]: 'Nueva Zelanda',
  [MemberNationality.NICARAGUA]: 'Nicaragua',
  [MemberNationality.NIGER]: 'Níger',
  [MemberNationality.NIGERIA]: 'Nigeria',
  [MemberNationality.NORTH_KOREA]: 'Corea del Norte',
  [MemberNationality.NORTH_MACEDONIA]: 'Macedonia del Norte',
  [MemberNationality.NORWAY]: 'Noruega',
  [MemberNationality.OMAN]: 'Omán',
  [MemberNationality.PAKISTAN]: 'Pakistán',
  [MemberNationality.PALAU]: 'Palaos',
  [MemberNationality.PALESTINE]: 'Palestina',
  [MemberNationality.PANAMA]: 'Panamá',
  [MemberNationality.PAPUA_NEW_GUINEA]: 'Papúa Nueva Guinea',
  [MemberNationality.PARAGUAY]: 'Paraguay',
  [MemberNationality.PERU]: 'Perú',
  [MemberNationality.PHILIPPINES]: 'Filipinas',
  [MemberNationality.POLAND]: 'Polonia',
  [MemberNationality.PORTUGAL]: 'Portugal',
  [MemberNationality.QATAR]: 'Catar',
  [MemberNationality.ROMANIA]: 'Rumania',
  [MemberNationality.RUSSIA]: 'Rusia',
  [MemberNationality.RWANDA]: 'Ruanda',
  [MemberNationality.SAINT_KITTS_AND_NEVIS]: 'San Cristóbal y Nieves',
  [MemberNationality.SAINT_LUCIA]: 'Santa Lucía',
  [MemberNationality.SAINT_VINCENT_AND_THE_GRENADINES]:
    'San Vicente y las Granadinas',
  [MemberNationality.SAMOA]: 'Samoa',
  [MemberNationality.SAN_MARINO]: 'San Marino',
  [MemberNationality.SAO_TOME_AND_PRINCIPE]: 'Santo Tomé y Príncipe',
  [MemberNationality.SAUDI_ARABIA]: 'Arabia Saudita',
  [MemberNationality.SENEGAL]: 'Senegal',
  [MemberNationality.SERBIA]: 'Serbia',
  [MemberNationality.SEYCHELLES]: 'Seychelles',
  [MemberNationality.SIERRA_LEONE]: 'Sierra Leona',
  [MemberNationality.SINGAPORE]: 'Singapur',
  [MemberNationality.SLOVAKIA]: 'Eslovaquia',
  [MemberNationality.SLOVENIA]: 'Eslovenia',
  [MemberNationality.SOLOMON_ISLANDS]: 'Islas Salomón',
  [MemberNationality.SOMALIA]: 'Somalia',
  [MemberNationality.SOUTH_AFRICA]: 'Sudáfrica',
  [MemberNationality.SOUTH_KOREA]: 'Corea del Sur',
  [MemberNationality.SOUTH_SUDAN]: 'Sudán del Sur',
  [MemberNationality.SPAIN]: 'España',
  [MemberNationality.SRI_LANKA]: 'Sri Lanka',
  [MemberNationality.SUDAN]: 'Sudán',
  [MemberNationality.SURINAME]: 'Surinam',
  [MemberNationality.SWEDEN]: 'Suecia',
  [MemberNationality.SWITZERLAND]: 'Suiza',
  [MemberNationality.SYRIA]: 'Siria',
  [MemberNationality.TAIWAN]: 'Taiwán',
  [MemberNationality.TAJIKISTAN]: 'Tayikistán',
  [MemberNationality.TANZANIA]: 'Tanzania',
  [MemberNationality.THAILAND]: 'Tailandia',
  [MemberNationality.TOGO]: 'Togo',
  [MemberNationality.TONGA]: 'Tonga',
  [MemberNationality.TRINIDAD_AND_TOBAGO]: 'Trinidad y Tobago',
  [MemberNationality.TUNISIA]: 'Túnez',
  [MemberNationality.TURKEY]: 'Turquía',
  [MemberNationality.TURKMENISTAN]: 'Turkmenistán',
  [MemberNationality.TUVALU]: 'Tuvalu',
  [MemberNationality.UGANDA]: 'Uganda',
  [MemberNationality.UKRAINE]: 'Ucrania',
  [MemberNationality.UNITED_ARAB_EMIRATES]: 'Emiratos Árabes Unidos',
  [MemberNationality.UNITED_KINGDOM]: 'Reino Unido',
  [MemberNationality.UNITED_STATES]: 'Estados Unidos',
  [MemberNationality.URUGUAY]: 'Uruguay',
  [MemberNationality.UZBEKISTAN]: 'Uzbekistán',
  [MemberNationality.VANUATU]: 'Vanuatu',
  [MemberNationality.VATICAN_CITY]: 'Ciudad del Vaticano',
  [MemberNationality.VENEZUELA]: 'Venezuela',
  [MemberNationality.VIETNAM]: 'Vietnam',
  [MemberNationality.YEMEN]: 'Yemen',
  [MemberNationality.ZAMBIA]: 'Zambia',
  [MemberNationality.ZIMBABWE]: 'Zimbabue',
} as const;

export const MemberSex = {
  FEMALE: 'female',
  MALE: 'male',
} as const;

export type MemberSex = (typeof MemberSex)[keyof typeof MemberSex];

export const MemberSexLabel = {
  [MemberSex.FEMALE]: 'Femenino',
  [MemberSex.MALE]: 'Masculino',
} as const;

export const MaritalStatus = {
  DIVORCED: 'divorced',
  MARRIED: 'married',
  SINGLE: 'single',
  WIDOWED: 'widowed',
} as const;

export type MaritalStatus = (typeof MaritalStatus)[keyof typeof MaritalStatus];

export const MaritalStatusLabel = {
  [MaritalStatus.DIVORCED]: 'Divorciado',
  [MaritalStatus.MARRIED]: 'Casado',
  [MaritalStatus.SINGLE]: 'Soltero',
  [MaritalStatus.WIDOWED]: 'Viudo',
} as const;
