export enum AppUrl {
  Enroll = '/enroll-account/:token',
  Home = '/',
  Login = '/login',
  LoginPasswordless = '/login/passwordless/:email',
  Logout = '/logout',
  Members = '/members',
  MembersEdit = '/members/:id',
  MembersNew = '/members/new',
  Movements = '/movements',
  MovementsEdit = '/movements/:id',
  MovementsNew = '/movements/new',
  Users = '/users',
  UsersEdit = '/users/:id',
  UsersNew = '/users/new',
  VerifyEmail = '/verify-email/:token',
}
