export const DIToken = Object.freeze({
  CategoryRepository: Symbol('CategoryRepository'),
  DueRepository: Symbol('DueRepository'),
  EmailService: Symbol('EmailService'),
  IMemberRepository: Symbol('IMemberRepository'),
  IMeteorUsers: Symbol('IMeteorUsers'),
  IPaymentDueRepository: Symbol('IPaymentDueRepository'),
  IPaymentRepository: Symbol('IPaymentRepository'),
  IUnitOfWork: Symbol('IUnitOfWork'),
  IUserRepository: Symbol('IUserRepository'),
  Logger: Symbol('Logger'),
  MemberMongoCollection: Symbol('MemberMongoCollection'),
  MovementFindPaginatedRepository: Symbol('MovementFindPaginatedRepository'),
  MovementRepository: Symbol('MovementRepository'),
  PaymentDueRepository: Symbol('PaymentDueRepository'),
  PaymentRepository: Symbol('PaymentRepository'),
});
