export enum MeteorMethodEnum {
  DuesCreate = 'dues/create',
  DuesGetGrid = 'dues/getGrid',
  DuesGetOne = 'dues/get',
  DuesGetPending = 'dues/getPending',
  DuesGetToExport = 'dues/getToExport',
  DuesGetTotals = 'dues/getTotals',
  DuesUpdate = 'dues/update',
  DuesVoid = 'dues/void',

  EventsGetGrid = 'events/getGrid',

  MembersCreate = 'members/create',
  MembersCreditGetAvailable = 'members-credit/getAvailable',
  MembersGet = 'members/get',
  MembersGetGrid = 'members/getGrid',
  MembersGetOne = 'members/getOne',
  MembersGetToExport = 'members/getToExport',
  MembersUpdate = 'members/updateNew',

  MovementsCreate = 'movements/create',
  MovementsDelete = 'movements/delete',
  MovementsGetGrid = 'movements/getGrid',
  MovementsGetOne = 'movements/get',
  MovementsGetToExport = 'movements/getToExport',
  MovementsGetTotals = 'movements/getTotals',
  MovementsRestore = 'movements/restore',
  MovementsUpdate = 'movements/update',
  MovementsVoid = 'movements/void',

  PaymentsCreate = 'payments/create',
  PaymentsGetGrid = 'payments/getGrid',
  PaymentsGetOne = 'payments/get',
  PaymentsGetTotals = 'payments/getTotals',
  PaymentsVoid = 'payments/void',

  PricesGetGrid = 'prices/getGrid',
  PricesGetOneByCategory = 'prices/getOneByCategory',

  UsersCreate = 'users/create',
  UsersGetByToken = 'users/getByToken',
  UsersGetGrid = 'users/getGrid',
  UsersGetOne = 'users/getOne',
  UsersUpdate = 'users/update',
  UsersUpdateTheme = 'users/updateTheme',
}
