name: 'dev'

on:
  push:
    branches:
      - dev

jobs:
  meteor-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Meteor
        run: curl https://install.meteor.com/ | sh

      - name: Install Dependencies
        run: meteor npm ci

      - name: Create Settings JSON
        uses: jsdaniell/create-json@v1.2.2
        with:
          json: ${{ vars.SETTINGS }}
          name: settings.json

      # - name: Create settings.json
      #   run: echo ${{ vars.SETTINGS }} > settings.json

      - name: Deploy
        run: |
          export METEOR_ALLOW_SUPERUSER=true
          export METEOR_SESSION_FILE=${{ fromJSON(secrets.METEOR_SESSION_FILE) }}
          export DEPLOY_HOSTNAME="galaxy.meteor.com"
          meteor deploy --free --mongo --settings settings.json --verbose
